myproject/course/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='dashboard'),
    path('courseView/', views.course_view, name='courses'),
    path('searchView/', views.search_view, name='search'),
    path('contentAdd/', views.content_add_view, name= 'content-add'),
    path('verification/', views.verification_view, name='verify'),
    path('<int:id>/contentEdit/', views.content_edit_view, name='content-edit'),
    path('<int:pk>/contentDelete/', views.content_delete_view, name='content-delete'),
    path('lecture/<int:lecture_id>/', views.tutorial_detail_view, name="tutorial"), 

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('course.urls')),
    path('user/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
  
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/course/models.py
from django.db import models
from django.conf import settings
from io import BytesIO  #basic input/output operation
from PIL import Image #Imported to compress images
from django.core.files import File #to store files
from django.core.exceptions import ValidationError

# Create your models here.

#Validate file size and limit upload size
def validate_file_size(value):
    file_size = value.size

    if file_size > 10485760:
        raise ValidationError('The maximum file size that can be uploaded is 10MB')
    else:
        return value

# Model with fields created for category page
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

# Model with fields created for course page 
class Course(models.Model):
    skill = (
        ('beginner', 'Beginner'),
        ('intermidate', 'Intermidate'),
        ('advance', 'Advance'),
        )
    title = models.CharField(max_length=500)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    poster = models.ImageField(upload_to='poster/', help_text = "Please upload a cover picture for your lecture slides.")
    skills = models.CharField(max_length=25,choices=skill)
    powerpoint_slides = models.FileField(upload_to='powerpoint/', null=True, blank=True, help_text = "Please upload your powerpoint slides here.")
    powerpoint_url = models.URLField( null=True, blank=True, help_text = "Please upload your powerpoint slides here.")
    price = models.IntegerField(null=True, blank=True, help_text = "Leave the table blank if the course is free of cost.")
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)
   
    def __str__(self):
        return self.title

# Model with fields created for verification page
class Verification(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    qualification = models.FileField(upload_to = 'documents/', null=True, help_text= 'Upload a proof for your verification to become an instructor.')
    verify = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email
    
# Model with fields created for lecture page 
class Lecture(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lecture_title = models.CharField(max_length=500, help_text= 'eg: Lecture 1: Introduction to computer')
    lecture_content = models.FileField(null=True, blank=True, upload_to='lecture video/', help_text='Upload your lecture video here', validators=[validate_file_size])
    youtube_url = models.URLField(null=True, blank=True, help_text='Link of youtube url that you want to upload')

    def __str__(self):
        return self.lecture_title

# Model with fields created for comment page
class Comment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    reply = models.ForeignKey('Comment', null=True, on_delete=models.CASCADE, related_name="replies") # this implies tha recursive relation to the reply field
    comment = models.TextField(max_length=200)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return '{}-{}'.format(self.course.title, str(self.user.full_name))

myproject/course/forms.py
from django import forms
from .models import Course, Comment, Verification

#Form created for content add
class ContentAddForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['title', 'category', 'poster', 'skills', 'powerpoint_slides', 'price']

        # widgets ={
        #     'title':forms.TextInput(attrs={'placeholder': 'Main title of the slide',}),
        #     'video_name':forms.TextInput(attrs={'placeholder': 'eg: Lecture 1: Intorduction to Computing'}),
            
        # }

#Form created to edit the content added
class ContentEditForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['title', 'category', 'poster', 'skills', 'powerpoint_slides', 'price']

# Form created for verifying a user
class VerificationForm(forms.ModelForm):

    class Meta:
        model= Verification
        fields = ['qualification',]

#Form created to for user to comment on the course
class CommentForm(forms.ModelForm):
    comment = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Comment goes here!!!', 'rows':'2', 'cols':'50'}))
    class Meta:
        model = Comment
        fields = ('comment',)

myproject/course/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, HttpResponse
from django.http import Http404 
from .models import Course, Lecture, Comment, Verification
from  accounts.models import Profile
from .forms import ContentAddForm, ContentEditForm, CommentForm, VerificationForm
from django.forms  import modelformset_factory
from django.contrib.auth import get_user_model
from accounts.decorators import allowed_users
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# Create your views here.

#method to render all the latest courses in dashboard
def home_view(request): 
    course_count = Course.objects.all().count()
    student_count = Profile.objects.filter(user__groups__name__in=['Student']).count()
    teacher_count = Profile.objects.filter(user__groups__name__in=['Teacher']).count()

    context = {
        'course_count': course_count,
        'student_count': student_count,
        'teacher_count': teacher_count
    }

    
    return render(request, 'apps/dashboard.html', context)


@login_required(login_url='login')
# method to load all the courses in the course page
def course_view(request):
    latest_course = Course.objects.all().order_by('-created')

    context = {
        'latest_course': latest_course,
    }

    return render(request, 'apps/course.html', context)

@login_required(login_url='login')
# method to search for particualr courses in the course page
def search_view(request):
   
    query = request.GET.get('q')

    if query:
        search = Course.objects.filter(
            Q(title__icontains=query)|
            Q(user__full_name=query)|
            Q(price__icontains=query)
        )
    context = {
        'search': search,
    }

    return render(request, 'apps/search.html', context)


    

@login_required(login_url='login')
# method to load each lecture and the comments associated with the particular course as per the user
def tutorial_detail_view(request, lecture_id):
    tutorial = get_object_or_404(Course, pk=lecture_id) # here we get the id and all its componenet associated with it
    comments = Comment.objects.filter(course=tutorial, reply=None).order_by('-id') # here we are filtering the comment for the relevent post and getting the latest post at the top

    # if the request is post than create a foprm object
    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)

        # if the form is valid than get the comment content and than create a comment object with the course detail, user detail and the comments detail and save it
        
        if comment_form.is_valid():
            comment = request.POST.get('comment') 
            reply_id = request.POST.get('comment_id')
            qs = None

            # for reply we first get the comment id
            # if there is reply than we get the reply id 
            if reply_id:
                qs = Comment.objects.get(id=reply_id)# to knw the reply of that comment by getting the reply id to the comment id

            comment = Comment.objects.create(course=tutorial, user=request.user, comment=comment, reply=qs)
            comment.save()

            return redirect('teacher-profile')
    
    
    else:
        comment_form = CommentForm()

    context = {
        'tutorial': tutorial,
        'comments': comments,
        'comment_form': comment_form,
    }

    return render(request, 'apps/lecture.html', context)
    

@login_required(login_url='login')
@allowed_users(allowed_roles=['Teacher']) # if the user is teacher than only the use can view the page
# method to add content to app by the user 
def content_add_view(request):
   
    LectureFormset = modelformset_factory(Lecture, fields=('lecture_title', 'lecture_content', 'youtube_url'))

    # if the request is post and the form is valid than save the form
    if request.method == 'POST':
        content_add_form = ContentAddForm(request.POST or None, request.FILES or None)
        formset = LectureFormset(request.POST or None, request.FILES or None)

        if content_add_form.is_valid() and formset.is_valid():
            course = content_add_form.save(commit=False)
            course.user = request.user
            course.save()

            # looping through the formset as we need multiple fields saving it in same form. here we get the data and than save it 
            for f in formset:
                try:
                    video = Lecture(course=course, lecture_title=f.cleaned_data.get('lecture_title'), lecture_content=f.cleaned_data.get('lecture_content'), youtube_url=f.cleaned_data.get('youtube_url'))
                    video.save()
                   
                except Exception as e:
                    break
            return redirect('teacher-profile')
    else:
        content_add_form = ContentAddForm()
        formset = LectureFormset(queryset=Lecture.objects.none())

    context = {
      
        'contentForm': content_add_form,
        'formset': formset,
    }
    
    return render(request, 'apps/contentAdd.html', context)


@login_required(login_url='login')
# method created for the verification from so that the user can upload the documents to become an instructor
def verification_view(request):
    if request.method == 'POST':
        
        verify_form = VerificationForm(request.POST or None, request.FILES or None)

        # if form is valid than we save the form in virutal database and we get the user and  than save the form in database
        if verify_form.is_valid():
            verify = verify_form.save(commit=False)
            verify.user = request.user
            verify.save()

    else:
        verify_form = VerificationForm() 
    
    context = {
        
        'verify_form': verify_form,
    }

    return render(request, 'apps/verification.html', context)




@login_required(login_url='login')
# Content Edit form
def content_edit_view(request, id):
    course = get_object_or_404(Course, pk=id)
    LectureFormset = modelformset_factory(Lecture, fields=('lecture_title', 'lecture_content', 'youtube_url'), extra=0)

    if course.user != request.user:
        raise Http404()

    if request.method == 'POST':
        content_edit_form = ContentEditForm(request.POST or None, request.FILES or None, instance=course)
        formset = LectureFormset(request.POST or None, request.FILES or None)

        if content_edit_form.is_valid(): 
            content_edit_form.save()
            data = Lecture.objects.filter(course=course)

            # give index of the item for a formset item strting form 0 and (f)the item itself 
            if formset.is_valid():
                for index, f in enumerate(formset):
                    if f.cleaned_data:
                        if f.cleaned_data['id'] is None:
                            video = Lecture(course=course, lecture_title=f.cleaned_data.get('lecture_title'), lecture_content=f.cleaned_data.get('lecture_content'), youtube_url=f.cleaned_data.get('youtube_url'))
                            video.save()
                        
                        else:
                            video = Lecture(course=course, lecture_title=f.cleaned_data.get('lecture_title'), lecture_content=f.cleaned_data.get('lecture_content'), youtube_url=f.cleaned_data.get('youtube_url'))              
                            d = Lecture.objects.get(id=data[index].id) #get slide id which was uploaded
                            d.lecture_title = video.lecture_title # changing the database tiitle with new title
                            d.lecture_content = video.lecture_content #changing the database content with new content
                            d.youtube_url = video.youtube_url # changing the database content with new content
                            d.save()

                return redirect('tutorial', course.id)

            else:
                print('formset is invalid')
    
        else:
            print("form is invalid")
          
    else:
        content_edit_form = ContentEditForm(instance=course)
        formset = LectureFormset(queryset=Lecture.objects.filter(course=course))

    context = {
        'contentForm': content_edit_form,
        'course': course,
        'formset': formset,
    }

    return render(request, 'apps/contentEdit.html', context)


@login_required(login_url='login')

# method for deleting the content that was uploaded. Here we get the id of the couser and if the method is post than we delete the object
def content_delete_view(request, pk):
    delete = get_object_or_404(Course, id=pk)
    if request.method == 'POST':
        delete.delete()
        return redirect('teacher-profile')

    return render(request, 'apps/contentDelete.html', {'delete': delete})

myproject/course/templates/apps/contentDelete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    
<!-- This is the confirmation page for delete function-->
    <form method = 'POST'>{% csrf_token %}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Content</legend>
            <h2> Are you sure you want to delete the content "{{ delete.title }}"</h2>
        </fieldset>

        <div class="form-group">
            <a class="btn btn-outline-secondary" href="{% url 'tutorial' delete.id %}"> Cancel</a>
            <button class="btn btn-outline-danger" type="submit"> Delete</button>
        </div>
    </form>
 
{% endblock %} 

   

myproject/course/templates/apps/course.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1 class="profile-heading mb-5"> Various Courses </h1>

<div class="row">
  <div class="col-12">
    <h4> Latest Courses</h4>
  </div>

</div>


<div class="row mb-5">

<div class="col-lg-12 col-carousel ">  

  <!-- Template which renders all the couser that has been upload by the user -->
          
    <div class="owl-carousel carousel-main">

      {% for latest in latest_course %}

            <div class="card latest-card">

              <a href="{% url 'tutorial' latest.id %}"> 

              <!-- Card image -->
                  <div class="latest-img">
                    <img class="card-img-top" src="{{latest.poster.url}}" alt="Card image cap">
                  </div>

                  <!-- Card content -->
                  <div class="card-body">

                    <!-- Title -->
                    <p class="card-title font-weight-bold"><a>{{ latest.title}}</a><p>
                    <!-- Data -->
                    <ul class="list-unstyled list-inline rating mb-0">
                      <li class="list-inline-item mr-0"><i class="fas fa-star amber-text"> </i></li>
                      <li class="list-inline-item mr-0"><i class="fas fa-star amber-text"></i></li>
                      <li class="list-inline-item mr-0"><i class="fas fa-star amber-text"></i></li>
                      <li class="list-inline-item mr-0"><i class="fas fa-star amber-text"></i></li>
                      <li class="list-inline-item"><i class="fas fa-star amber-text"></i></li>
                      <li class="list-inline-item"><p class="text-muted">4.5 (413)</p></li>
                    </ul>
                    <p>{{latest.user.full_name | capfirst}}</p>

                    {% if course.price %}
                      <p class="mb-2">Rs.{{latest.price}}</p> 
                    {% else %}
                      <p class="mb-2">Free</p>
                    {% endif %}

                  </div>
                  </a>
              </div>

              {% empty %}
              <div class="container-fluid">
                <h3> No post found having search query {{ request.GET.q }}</h3>
              </div>
            {% endfor %}

      </div>

  </div>
</div>
<div class="line"></div>



{% endblock %} 

{% block scripts %}

<script type="text/javascript">

  $('.carousel-main').owlCarousel({
    autoPlay: false,
    center: true,
    items: 3,
    loop: true,
    stopOnHover : true,
    autoplayTimeout: 1500,
    margin: 10,
    navigation: true,
    dots: false,
    navigationText: ['<span class="fas fa-chevron-left fa-2x"></span>','<span class="fas fa-chevron-right fa-2x"></span>'],
  });

</script>
    
{% endblock scripts %}

myproject/course/templates/apps/lecture.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- We get the user information that as added the course-->
<div class="row mb-2">
    <div class="col-9">
      <h1>{{ tutorial.title}}</h1>
      <h5>{{ tutorial.user| capfirst}}</h5>
      
    </div>

    <!-- if the course is realted to the user than they can delete or edit the course-->
    <div class="col-mb-3">
      {% if tutorial.user == request.user %}

      <a href="{% url 'content-edit' tutorial.id %}"><button class="btn btn-secondary">Edit Content</button></a>
      <a href="{% url 'content-delete' tutorial.id %}"><button class="btn btn-danger">Delete Content</button></a>
    
    {%endif%}
    </div>
  </div>

  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Lecture Youtube Links</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Lecture Video</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">lecture Powerpoint Slides</a>
    </li>
  </ul>
  <div class="tab-content" id="pills-tabContent">

    <!------------Youtube -------------->
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="row">
   
        <div class="col-lg-4 col-sm-12 playlist">
       
         
           {% for slides in tutorial.lecture_set.all %}

           {% if slides.youtube_url %}
           
             <a href="{{slides.youtube_url}}" target="iframe_a">
               
              <div class="row mt-2">
              
 
                <div class="col-lg-3">
                 <img src="{{slides.course.poster.url}}" class="img-fluid" alt="lecture slides">
                </div>
 
                <div class="col-lg-9">
                  <p>{{slides.lecture_title}}</p>
                </div>
              </div>
               
             </a>
          
           <hr>

           
         {% else  %}

         <p> There are no slides uploaded.</p>

         {% endif %}
           
           {% endfor %}

     </div>
    
     <div class="col-lg-8 col-sm-12">
 
       <iframe class="frame" src="" name="iframe_a" id="fitvid0" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
 
       
     </div>
 
  
   </div>
    </div>

    <!-----------------Video ------------------>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">

      <div class="row" id="video_player">
   
        <div class="col-lg-4 col-sm-12 playlist">
 
          {% for slides in tutorial.lecture_set.all %}

          {% if slides.lecture_content %}
           
          <a href="{{slides.lecture_content.url}}">
            
           <div class="row mt-2">
           

             <div class="col-lg-3">
              <img src="{{slides.course.poster.url}}" class="img-fluid" alt="lecture slides">
             </div>

             <div class="col-lg-9">
               <p>{{slides.lecture_title}}</p>
             </div>
           </div>
            
          </a>
       
        <hr>

         {% else  %}

            <p> There are no slides uploaded.</p>

            {% endif %}
        {% endfor %}
     </div>
    
     <div class="col-lg-8 col-sm-12 videoarea">

      <video class="frame" muted controls controlslist="nodownload" data-autoplay-on-select="true" data-showing-captions="true" poster="{{ tutorial.poster.url }}" id="videoarea">
         <source src="" type="video/mp4">
         <source src="" type="video/webm">
 
     </div>
 
  
   </div>
    </div>

    <!-----------------Powerpoint ------------------>
    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
      <div class="row">
        <div class="col-lg-12">
              {% if tutorial.powerpoint_url %}
                <iframe src="{{tutorial.powerpoint_url|safe}}" width="1000px" height="500px" frameborder="0"></iframe>
              {% else %}
              <h1 class="text-center font-weight-bold "> There is no slide uploaded</h1>
              {% endif %}
        
          
          </div>
      </div>
    </div>
  </div>  

         <!-----------------Lecture Description ---------------------------->

    <div class="row mt-5"><!-----------row open -------->
        <div class="col-lg-8">
              <ul class="nav nav-tabs">

               <li class="nav-item">
                  <a class="nav-link active" href="#home"data-toggle="tab">Overview</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#comments">Q&A</a>
                </li>
                 
              </ul>

                <div class="tab-content my-4"> <!------Tab content open---->

                    <div id="home" class="tab-pane active">
                      <h3>About this Course</h3>
                      <hr>

                      <div class="row">
                        <div class="col-lg-4">
                          <p class="font-weight-bold">By the number:</p>
                        </div>

                        <div class="col-lg-">
                          <p>Skills:{{tutorial.skills| capfirst}} </p>
                          <p>Language:English</p>
                          <p>Hours:29hr</p>
                          <p>Caption:No</p>
                        </div>
                      </div>
                      <hr>

                      <div class="row">
                        <div class="col-lg-4">
                          <p class="font-weight-bold">PowerPoint Slide:</p>
                        </div>

                        <div class="col-lg-4">
                          {% if tutorial.powerpoint_slides %}
                            <a href="{{ tutorial.powerpoint_slides.url}}" class="btn btn-primary" target="_blank"> Download SLides</a>
                          {% else %}
                            <p> N/A </p>
                          {% endif %}
                        </div>
                      </div>
                      <hr>

                      <div class="row">
                        <div class="col-lg-4">
                          <p class="font-weight-bold">Description:</p>
                        </div>

                        <div class="col-lg-5">
                          <span>What you will learn?</span>
                         
                          <ul>
                            {% for slides in tutorial.lecture_set.all %}
                              <li>{{ slides.lecture_title}}</li>
                            {% endfor %}
                          </ul>
                      
                        </div>
                      </div>

                    </div>

                    <div id="comments" class="tab-pane">


                   <!------------For Comment section---------->

                      {{ comments.count}} Comment{{ comments|pluralize}}
                      <hr>

                    <div class="main-comment-section">

                      <div class="container-fluid mt-2">
                        <div class="form-group row">
                          <form method="POST" class="comment-form">
                            {% csrf_token %}
                            {{ comment_form.as_p }}
                            {% if request.user.is_authenticated %}
                              <input type="submit" value="Comment" class="btn btn-outline-success">
                            {% else %}
                              <input type="submit" value="Comment" class="btn btn-outline-success" disabled>
                            {% endif %}
                          </form>
                        </div>
                      </div>

                   

                        {% for comment in comments %}

                       <!------------To view the comment---------->
                        <blockquote class="blockquote">
                          <p class="mb-0"><small>{{ comment.comment}}</small></p>
                          <footer class="blockquote-footer"><small><cite title="Source Title">{{ comment.user|capfirst}} </cite></small>
                            <button type="button" name="button" class="reply-btn btn btn-outline-dark-sm ml-2">Reply{{ comment.count}}</button></footer>
                        </blockquote>

                         <!------------To reply comment---------->
                        <div class="replied-comments container mt-2" style="display:none;">
                          
                          {% for reply in comment.replies.all %}

                          <blockquote class="blockquote">
                            <p class="mb-0"><small>{{ reply.comment }}</small></p>
                            <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ reply.user|capfirst }}</cite></small></footer>
                          </blockquote>
                          {% endfor %}

                           <!------------To write reply for the comment---------->
                          <div class="form-group row">
                            <form method="POST" class="comment-form">
                              {% csrf_token %}
                              <input type="hidden" name="comment_id" value="{{ comment.id }}">
                              {{ comment_form.as_p }}

                              {% if user.is_authenticated %}
                                <input type="submit" value="Reply" class="btn btn-outline-success">
                              {% else %}
                                <input type="submit" value="Reply" class="btn btn-outline-success" disabled>
                              {% endif %}
                            </form>
                          </div>
                        </div>

                        {% endfor %}
                    </div>
                                    

                      </div>
                     
             
                </div><!------ Tab content close---->
        </div>
    </div><!-----------------row close ------------->

    {% block scripts %}

    <script type="text/javascript">

      // reply button
        $(document).ready(function(event){
            $('.reply-btn').click(function() {
            $(this).parent().parent().next('.replied-comments').fadeToggle()
          });
        }); 


    // video player
      var video_player = document.getElementById("video_player"),
      links = video_player.getElementsByTagName('a');
      for (var i=0; i<links.length; i++) {
        links[i].onclick = handler;
      }

          function handler(e) {
            e.preventDefault();
            videotarget = this.getAttribute("href");
            filename = videotarget.substr(0, videotarget.lastIndexOf('.')) || videotarget;
            video = document.querySelector("#video_player video");
            video.removeAttribute("poster");
            source = document.querySelectorAll("#video_player video source");
            source[0].src = filename + ".mp4";
            source[1].src = filename + ".webm";
            video.load();
            video.play();    
          }

        
         
  </script>
    
    {% endblock scripts %}

 

   

{% endblock %} 

myproject/course/templates/apps/verification.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}
    
<div class="row">
    <div class="col-12 col-sm-auto mb-3">
      <div class="user-media">
         <img class="mb-3 rounded-pill shadow-sm mt-1" src="{{user.profile.profile_img.url}}" alt="profile-img">
      </div>
    </div>
    <div class="col d-flex flex-column flex-sm-row justify-content-between mb-3">
      <div class="text-center text-sm-left mb-2 mb-sm-0">
        <h4 class="pt-sm-2 pb-1 mb-0 text-nowrap">{{ user.full_name}}</h4>           
      </div>
     
    </div>
  </div>
  
  <!-- Form created to make sure the use to verified to become an instructor-->
  <ul class="nav nav-tabs">
    <li class="nav-item"><a href="" class="active nav-link">Verify Document</a></li>
  </ul>


  <div class="tab-content pt-3">
    <div class="tab-pane active" id="item-template">


      <form method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
     
            <div class="row">
              <div class="col-lg-12">
                
                  <p>
                  Please upload your proof of qualification here for verification to become an instructor

                <div class="row">
                    <div class="col-lg-6">
                        {{verify_form.qualification| as_crispy_field}}
                    </div>
                </div>

              
                  <div class="text-center">
                    <button type="submit" class="btn btn-submit"><i class="fa fa-paper-plane"></i> Submit</button>
                  </div>
              </div>
          </div>
      </form>

            
          </div>



    </div>

 
{% endblock %} 

   